---
- name: Install Ruby && Bundler
  hosts: all
  become: true
  tasks:
  # Установим в цикле все зависимости
  - name: Install ruby and rubygems and required packages
    apt: 
      name: ruby-full 
      state: present
  - name: Install ruby and rubygems and required packages
    apt: 
      name: ruby-bundler 
      state: present
  - name: Install ruby and rubygems and required packages
    apt: 
      name: build-essential 
      state: present